Documents/urls.py
from django.http import * 
from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.urls import path 
from .views import *


app_name = 'documentos'

urlpatterns = [
     path('', index, name="documentos"),
     path('create/<tipo>', create, name='create'),
     path('choose/', choose_document, name='chooseType'),
     path('edit/<codigo>', edit, name='edit'),
     path('details/<id>', get_document, name='details'),
     path('createCategory/', createCategory, name='createCategory'),
     path('categories/', getCategories, name='categories'),
     path('editCategoryType/<id>', editCategory, name='editCategoryType'),

     
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import *
from core import settings
from django.conf.urls.static import static

from .views import *
urlpatterns = [
    path('', home , name='home'),
    path('Admin/', admin.site.urls),
    path('Signin/', signin, name='signin'),
    path('Signup/', signup, name='signup'),
    path("Logout/",signout, name="logout"),
    path('users/', users, name='users'),
    # path('editUser/<id>', editUser, name='editUser'),
    
    path('users/edit/<id>', modifyUser, name='usersModify'),
    
    path('myProfile/', myProfile, name='myProfile'),

    path('Documentos/', include('Documents.urls'),name='documentos'),
    path('Usuarios/', include('users.urls', namespace='usuarios')),
    
    path('users/create/', createUser, name='createUser'),


    
    path('oauth/', include('social_django.urls', namespace='social')),  

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# =======
# """core URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/3.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path,include
# from django.shortcuts import *
# from core import settings
# from django.conf.urls.static import static

# from .views import *
# urlpatterns = [
#     path('', home , name='home'),
#     path('Admin/', admin.site.urls),
#     path('Signin/', signin, name='signin'),
#     path('Signup/', signup, name='signup'),
#     path("Logout/",signout, name="logout"),
#     path('Documentos/', include('Documents.urls'),name='documentos'),
#     path('Usuarios/', include('users.urls', namespace='usuarios')),
#     path('usuarios/', include('users.urls', namespace='usuarios')),
#     path('oauth/', include('social_django.urls', namespace='social')),  

# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# >>>>>>> master

Documents/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Basedocumento(models.Model):
    idtipodocumento = models.ForeignKey('Tipodocumento', models.DO_NOTHING, db_column='idtipodocumento', blank=True, null=True)
    atributo = models.CharField(max_length=100, blank=True, null=True)
    tipodato = models.CharField(max_length=100, blank=True, null=True)
    class Meta:
        managed = True
        db_table = 'basedocumento'


class Detalledocumento(models.Model):
    iddocumento = models.ForeignKey('Documento', models.DO_NOTHING, db_column='iddocumento', blank=True, null=True)
    atributo = models.CharField(max_length=100, blank=True, null=True)
    tipodato = models.CharField(max_length=100, blank=True, null=True)
    valor = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'detalledocumento'
        
        
class Documento(models.Model):
    iddocumento = models.BigAutoField(primary_key=True)
    idtipodocumento = models.ForeignKey('Tipodocumento', models.DO_NOTHING, db_column='idtipodocumento', blank=True, null=True)
    titulo = models.CharField( max_length=100, blank=True, null=True)
    portada = models.ImageField(upload_to='documents/portadas', blank=True, null=True)
    fechasubida = models.DateTimeField(auto_now_add=True)
    ruta = models.FileField(upload_to='documents', blank=True, null=True)
    
    publico = models.BooleanField(default=False)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    estado = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
            return self.name
    
    class Meta:
        managed = True
        db_table = 'documento'
        
        
class Tipodocumento(models.Model):
    idtipodocumento = models.BigAutoField(primary_key=True)
    imagen = models.ImageField(upload_to= 'documents/category_type', blank=True, null=True)
    tipo = models.CharField(unique=True, max_length=30, blank=True, null=True)
    descripcion = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'tipodocumento'
    # def __str__(self):
    #     return self.tipo

Documents/views.py
import os
from django.shortcuts import render
from django.shortcuts import redirect
from django.core.files.storage import default_storage
from django.core.files import File
from core import settings
from .forms import *
from django.http import HttpResponse, Http404
import mimetypes
from .models import Tipodocumento, Documento
from django.db import connection
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from core.choices2 import *
from django.core.paginator import Paginator
from django.contrib import messages

# from ..core import settings

# Create your views here.

@login_required(login_url='signin' , redirect_field_name = 'documentos')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def index(request):
    tipos = Tipodocumento.objects.all() 
    #Home muestra los documentos que fueron establecidos:      
    docs = Documento.objects.all()
    docs  = Documento.objects.all().filter(usuario=request.user.id)
    searchKey = request.POST.get("key", "searchKey")
    
    for doc in docs:        
        if(doc.portada):
            if(os.path.exists(os.getcwd() + doc.portada.url) == False):
                doc.portada = doc.idtipodocumento.imagen
        else:
            doc.portada = doc.idtipodocumento.imagen
            
    texto = request.GET.get('texto')

    todo_seleccionado = request.GET.get("allSelected")

    documentosMarcados = request.GET.getlist('activo') 
    documentosMarcadosDos = request.GET.getlist('activo') 

    for tipo in tipos:
        tipo.activado = True

    if (todo_seleccionado == "true"):
            for tipo in tipos:
                documentosMarcados.append(tipo.idtipodocumento)

    if documentosMarcados:
        for tipo in tipos:
            encontrado = False
            for idtipo in documentosMarcados:
                if  tipo.idtipodocumento == int(idtipo):
                    encontrado = True
            tipo.activado = encontrado            
    
    searchKey = request.GET.get("key", "searchKey")
    if not documentosMarcados:
        for tipo in tipos:
            documentosMarcados.append(tipo.idtipodocumento)
    
    if texto != None:
        docs = docs.filter(titulo__contains = texto, idtipodocumento__in = documentosMarcados)
    else:
        texto = ""
        docs = docs.filter(titulo__contains = "", idtipodocumento__in = documentosMarcados)

    #Verificar que exista la imágen de los documentos, si no existe usar la de la categoría.
    for doc in docs:
        if(doc.portada):
            if(os.path.exists(os.getcwd() + doc.portada.url) == False):
                doc.portada = doc.idtipodocumento.imagen
        else:
            doc.portada = doc.idtipodocumento.imagen 



    if (todo_seleccionado == "true"):
        if documentosMarcadosDos:
            for tipo in tipos:
                encontrado = False
                for idtipo in documentosMarcadosDos:
                    if  tipo.idtipodocumento == int(idtipo):
                        encontrado = True
                tipo.activado = encontrado        
    else:
        todo_seleccionado = "false"

    max_elements_per_page = 12

    paginator = Paginator(docs, max_elements_per_page)
    page_number = request.GET.get('page') or 1
    page_obj = paginator.get_page(page_number)

    div_agregar= []
    if max_elements_per_page % 2 != 0:
        max_elements_per_page = max_elements_per_page + 2
    div_agregar.append(range(max_elements_per_page-len(docs)))
    return  render(request,'core/home.html',{'todo_seleccionado': todo_seleccionado, 'div_agregar': div_agregar, 'texto':texto, 'docs':page_obj, 'categories': tipos, 'page_obj': page_obj, 'searchKey': searchKey})

@login_required
def edit(request, codigo):
    
    modal=  ["Editar documento","¿Desea guardar cambios?","Cancelar","Guardar"]

    
    registro = Documento.objects.get(iddocumento = codigo)
    choices = Tipodocumento.objects.all();
    atributosDocumento = Detalledocumento.objects.filter(iddocumento = codigo);
    estados = ["En análisis", "Aceptado", "Rechazado", "No revisado"]
    tiposAtributos = TIPOS_ATRIBUTO

    if request.method == 'POST':        
        documentoEdit = Documento.objects.get(iddocumento = codigo)
        documentoEdit.titulo = request.POST["in_titulo"]
        
        if(request.POST.get("in_ruta") == ''):
            print("No Válido")
        else:
            print("Válido")
            documentoEdit.ruta = request.FILES["in_ruta"]
        

        tipoDoc = Tipodocumento.objects.get(idtipodocumento=request.POST["in_tipodocumento"])
        documentoEdit.idtipodocumento = tipoDoc
        documentoEdit.estado = request.POST["in_estado"]

        ids_detallesOriginal = request.POST.getlist('idsDetalleOriginal')

        detalle_atributos = request.POST.getlist('atributoModificado')
        detalle_tipo = request.POST.getlist('tipoModificado')
        valor_atributos = request.POST.getlist('valorModificado')
        ids_detalles = request.POST.getlist('idsDetalle')

        detalle_atributos_Nuevo = request.POST.getlist('atributoNew')
        detalle_tipo_Nuevo = request.POST.getlist('tipoDatoNew')
        valor_atributos_Nuevo = request.POST.getlist('valorNew')

        for i in range (len(ids_detalles)):           
            detalleEditar = Detalledocumento(id=ids_detalles[i], atributo=detalle_atributos[i], tipodato = detalle_tipo[i], valor = valor_atributos[i], iddocumento = documentoEdit)            
            ids_detallesOriginal.remove(ids_detalles[i]);
        
        for i in range (len(valor_atributos_Nuevo)):           
            detalleEditar = Detalledocumento( atributo=detalle_atributos_Nuevo[i], tipodato = detalle_tipo_Nuevo[i], valor = valor_atributos_Nuevo[i], iddocumento = documentoEdit )
            detalleEditar.save();

        for i in range  (len(ids_detallesOriginal)):
            detalleEliminar = Detalledocumento.objects.get(id = ids_detallesOriginal[i]);
            detalleEliminar.delete();
        

        documentoEdit.save()
        
        messages.add_message(request, messages.SUCCESS, 'Documento editado exitosamente')
        return redirect( 'home')
    else: 
        return render(request, 'documents/edit_document.html', {'modal':modal, 'tAtributos': tiposAtributos, 'frmAtributos':frmDetalleDocumento, 'form':frmCrearCuenta, 'registro': registro, 'codigo':codigo, 'choices':choices, 'estado':estados, 'atributosDocumento':atributosDocumento})


def choose_document(request):
    if request.method == 'POST':
        pass
    else:
        tipos = Tipodocumento.objects.all()
        return render(request,'documents/choose_document_type.html', {'tipos': tipos})
    
@login_required  
def get_document(request, id):    
 if request.method == 'POST':
        pass
 else:
        registro = Documento.objects.get(iddocumento = id)
        atributos = Detalledocumento.objects.filter(iddocumento = id)
        tipodoc = Tipodocumento.objects.all()

    
        if(registro.portada):
            if(os.path.exists(os.getcwd() + registro.portada.url) == False):
                registro.portada = registro.idtipodocumento.imagen
        else:
            registro.portada = registro.idtipodocumento.imagen
        if registro.portada is None:
            registro.portada = registro.idtipodocumento.imagen

        i = 0;
        #Obtener otros documentos:
        docsAlt = Documento.objects.all().order_by("iddocumento")
        docsAlt.aget_or_create('columnNumberAdd')

        fileSize = 0

        for doc in docsAlt:                        
            doc.columnNumber = (doc.iddocumento % 3) + i
            if(doc.portada):
                if (os.path.exists(os.getcwd() + doc.portada.url) == False):
                    doc.portada = doc.idtipodocumento.imagen
                else:
                    fileSize = round(os.path.getsize(os.getcwd() + registro.ruta.url) * 10**-6, 2)
            else:
                doc.portada = doc.idtipodocumento.imagen
               

        paginator = Paginator(docsAlt, 3)
        page_number = request.GET.get('page') or 1
        page_obj = paginator.get_page(page_number)
        
        columnsToAdd = []       
        if len(docsAlt)  % 2 == True:
            columnsToAdd.append(range(2))
        else:
            columnsToAdd.append(range(1))

        return render(request,'documents/details_doc.html', {'fileSize': fileSize, 'registro': registro, 'atributos': atributos,'tipos': tipodoc, 'docsAlt': page_obj, 'page_obj': page_obj, 'columnsToAdd': columnsToAdd})   
      

def createCategory(request):    
    modal=  ["Editar documento","¿Desea guardar cambios?","Cancelar","Guardar"]

    if request.method == 'POST':
        frm = frmCrearCategoria(request.POST, request.FILES)
        
        if frm.is_valid():
            frm.save()
            messages.add_message(request, messages.SUCCESS, 'Categoria creada exitosamente')

            last_cat = Tipodocumento.objects.last()
            
            detalle_atributos_Nuevo = request.POST.getlist('atributoNew')
            detalle_tipo_Nuevo = request.POST.getlist('tipoDatoNew')
            
            
            for i in range (len(detalle_atributos_Nuevo)):
                base_doc = Basedocumento(idtipodocumento = last_cat, atributo = detalle_atributos_Nuevo[i], tipodato = detalle_tipo_Nuevo[i])
                base_doc.save()
            frm.save()
            return redirect('documentos:categories')
        else :            
            return render(request, 'documents/createCategory.html', {'modal':modal, 'tAtributos': tiposAtributos, 'frmAtributos':frmDetalleDocumento, 'form':frm})

        
        
    else:
        frm = frmCrearCategoria

templates/documents/choose_document_type.html
{% extends 'core/base.html' %} 
{% block title %}Crear documento - Tipo documento{% endblock title %}
{% load static %}

{% block content %}
  
<link rel="stylesheet" href="{% static 'css/subirdoc.css' %}">

<div class="container">
  <div class="row m-3">
    {% for tipo in tipos %}

    <div class="col-sm-12 col-md-4 col-lg-3 col-xl-2">
      <div class="col mb-3">
        <div class="card h-100">
          <img src="{{tipo.imagen.url}}" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title">{{tipo.tipo}}</h5>
            <p class="card-text">{{tipo.descripcion}}</p>
          </div>
          <a class="btn-a" href="{% url 'documentos:create' tipo=tipo.idtipodocumento %}">Subir {{tipo.tipo}}</a>
        </div>
      </div>
    </div>

    {% endfor %}


    



  </div>
</div>
{% endblock content %}


templates/documents/details_documents.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}


<div class="container">
    <label class="form-label">Titulo</label>
    <input name="in_titulo" class="form-control" type="text" value="{{registro.titulo}}" />
</div>

<div class="container">
    <label class="form-label">Ruta</label>
    <input name="in_ruta" class="form-control" type="file" value="{{registro.ruta}}" />
</div>  

{% comment %} <div class="container">
    <label class="form-label">Tipo de documento</label>
    
    <select name="in_tipodocumento" class="form-control">
        {% for item in tipo %}
            <option value="{{item.idtipodocumento}}">{{item.tipo}}</option>
        {% endfor %}
    </select>

</div>       {% endcomment %}




{% for item in  atributos %}
<label  class="form-label" for="">{{item.atributo}} </label>    
<input class="form-control"  type="{{item.tipodato}}" name="atributo" id="" value="{{item.valor}}" disabled>

{% endfor %}


{% endblock content %}


templates/documents/docs_content.html
{% extends 'core/home.html' %}
{% load static %}


{% block docscontent %}



    <div class="col col-9">
        <div class="row">

        {% for doc in docs  %}
            <div class="col-xl-2 col-lg-4 col-md-6 col-sm-12 my-2">
            
                <div>
                    <img class="img-fluid"  src="{{doc.portada.url}}" alt="">
                </div>
                
            </div>


            {% endfor %}
        </div>

        
    
    </div>

{% endblock docscontent %}

templates/documents/documentType_create.html
{% load static %}
{% extends 'core/base.htmk' %}


{% block content %}

{% endblock content %}

templates/documents/documentsType.html
{% extends 'core/base.html' %}
{% block title %}Crear Tipo de documento{% endblock title %}

{% block content %} 
<div class="container mt-2">
    <a href="{% url 'documentos:createCategory'%}" class="btn btn-success">Agregar nuevo tipo</a>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Tipo de documento</th>
        <th scope="col">Descripción</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for item in categories %}
      <tr>
        <th>{{item.tipo}}</th>        
        <td>{{item.descripcion}}</td>
        <td>
          <a href="../../Documentos/editCategoryType/{{item.idtipodocumento}}" class="btn btn-warning">Modificar</a>
        </td>       
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>
{% endblock content %}


templates/documents/edit_category.html
{% extends 'core/base.html' %}
 {% load static %} 
 {% block title %}Crear Tipo de documento{% endblock title %}
  {% block content %}

<div class="container">
  <div class="row">    
    <form  id="form-main"  action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{frmDetalleDocumento}}
      <div class="col">
        <label for="id_tipo">Tipo de Documento:</label>

        <input  type="text" name="tipo" class="form-control"maxlength="30" id="id_tipo" value = "{{categories.tipo}}" />

        <label for="id_imagen">Imagen:</label>
          <!--Aqui inicia el modal-->
          <div div class="modal modal-dialog modal-lg" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog" style="max-width: 80% !important;" role="document">
            <div class="modal-content">
                <!-- Cabecera del modal-->
                <div class="modal-header">
                <h4 class="modal-title text-al">Categorías: {{categories.tipo}}</h4>
                <button button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <!-- Imagen -->
                <div class="modal-body justify-content-center">
                <iframe class="text-center" src="{{categories.imagen.url}}" width="100%" height="300px" id="myframe"></iframe>
                </div>

            </div>
            </div>
        </div>
        <div class="row">
          <div class="col-8">
              <input name="in_ruta" class="form-control" type="file" value="{{registro.ruta.url}}" />
          </div>
          <div class="col">
            <button data-bs-toggle="modal" data-bs-target="#staticBackdrop" class="form-control btn btn-primary" type="button">Abrir archivo</button>

          </div>
      </div>

        

        <label for="id_descripcion">Descripción:</label>

        <input type="text" name="descripcion" class="form-control" maxlength="100" id="id_descripcion" 
          value = "{{categories.descripcion}}" />

        <div class="col-12 text-end mt-2">
          <input  class= "btn btn-primary"  value="Guardar" data-bs-toggle="modal" data-bs-target="#exampleModal" >
        </div>
      </div>

      <div class = "container border border-black border-2 rounded p-3" style = "width: 97%;">
        {% for item in detallesCategoria  %}                            
            <input name="idsDetalleOriginal" type="hidden" value="{{item.id}}"/>
            <div class="atributoContenedor">                                
                <div class = "container">
                    <input name="idsDetalle" type="hidden" value="{{item.id}}"/>
                    <label class = "form-label fw-bold">Atributo:</label>      

                    <input class="btn btn-outline-info justify-content-between" type="button" value = "-" onclick=" deleteAttribute(event);
                            function deleteAttribute(e){
                            var buttonClicked = e.target;
                            buttonClicked.parentElement.parentElement.remove();
                        }
                    " style="float:right"/>

                    <input class="btn btn-outline-info justify-content-between" type="button" value = "^" onclick="showAndHide(event)" style="float:right"/>
                    <input name ="atributoModificado" type="text" class = "form-control" value="{{item.atributo}}" />
                </div>    
                <div class="container" style="visibility: hidden; display:none;">
                  <label class="form-label">Tipo de dato:</label>
                  <select name="tipoDatoModificado" class="form-select" onchange="onChangeTypeData(event)">
                  {% for tAtributo in tiposAtributo %}                  
                    {% if tAtributo.0 == item.tipodato %}
                      <option value="{{tAtributo.0}}" class="form-control" selected>
                        {{tAtributo.1}}
                      </option>
                    {% else %}
                      <option  value="{{tAtributo.0}}" class="form-control" >
                        {{tAtributo.1}}
                      </option>
                    {% endif %}
                  {% endfor %}                  
                </select>
                  <label class="form-label">Previsualización:</label>
                  <input class="form-control" type="{{item.tipodato}}" readonly="true" />
                </div>                 
            </div>          
            <br>
        {% endfor %}

        <div class = "d-flex justify-content-between container">
          <label class="form-label fw-bold">Nuevos atributos</label>  
          <div class="text-end">
              <input class="btn btn-outline-info" type="button" value = "+" onclick="clicAddAttribute(event)"/>
          </div>    
      </div>
      <br> 
      <div id="nuevosAtributos" class = "container border border-black border-2 rounded p-3" style = "width: 95%;">

      </div>  
    </div>    
    </form>
  </div>
</div>
<script>
function clicAddAttribute(e){
    // create a new div element
    const contenedor = document.getElementById("nuevosAtributos");
  
    const newDiv = document.createElement("div");
    newDiv.id = "atributoContenedor";

    const newlabel = document.createElement("label");
    newlabel.className = "form-label fw-bold";
    newlabel.textContent = "Atributo";        

    const newInput = document.createElement("input");
    newInput.className = "form-control";
    newInput.type="text";
    newInput.name="atributoNew";

    const labeltipoDato = document.createElement("label");
    labeltipoDato.className = "form-label fw-bold";
    labeltipoDato.textContent = "Tipo de dato";        
    
    const inputTipoDato = document.createElement("input");
    inputTipoDato.className = "form-control";
    inputTipoDato.type="text";
    inputTipoDato.name="tipoDatoNew";

    const atributosDisponibles = document.getElementById("id_tipodato");       
    const selectTipoDato = atributosDisponibles.cloneNode(true);
    selectTipoDato.removeAttribute("hidden");
    selectTipoDato.name = "tipoDatoNew";

    selectTipoDato.onchange = ('onChangeTypeData', () => onChangeTypeData(event))
    const newlabelValue = document.createElement("label");
    newlabelValue.className = "form-label fw-bold";
    newlabelValue.textContent = "Previsualización:";        

    const valueInput = document.createElement("input");
    valueInput.className = "form-control";
    valueInput.type= "text";
    valueInput.name= "valorNew";

    const divBarraNuevoAttribute = document.createElement("div");
   
    divBarraNuevoAttribute.id = "divBarraAtributo";

    const inputDeleteAttribute = document.createElement("input");
    inputDeleteAttribute.type = "button";
    inputDeleteAttribute.id = "deleteAttribute";
    inputDeleteAttribute.value = " -";
    inputDeleteAttribute.className = "btn btn-outline-info justify-content-between";
    inputDeleteAttribute.style = "float: right";

    inputDeleteAttribute.onclick = ('onClick',() => deleteAttribute(event))

    const minimizeAttribute  = document.createElement("input");
    minimizeAttribute.type = "button";
    minimizeAttribute.id = "minimizeAttribute";
    minimizeAttribute.className = "btn btn-outline-info justify-content-between";
    minimizeAttribute.style = "float: right";
    minimizeAttribute.value = "^";
    minimizeAttribute.onclick = ('onClick',() => showAndHide(event));

    //contenedor.appendChild(newlabel);
    divBarraNuevoAttribute.style.display = "block";

    divBarraNuevoAttribute.appendChild(newlabel);
    divBarraNuevoAttribute.appendChild(inputDeleteAttribute);
    divBarraNuevoAttribute.appendChild(minimizeAttribute);
    divBarraNuevoAttribute.appendChild(document.createElement("br"));
    divBarraNuevoAttribute.appendChild(newInput);
    

    const divContentAttribute = document.createElement("div");        
    divContentAttribute.id = "divBarraAtributo";

    divContentAttribute.appendChild(labeltipoDato);
    //divContentAttribute.appendChild(inputTipoDato);
    divContentAttribute.appendChild(selectTipoDato);

    divContentAttribute.appendChild(newlabelValue);
    divContentAttribute.appendChild(valueInput);
    valueInput.readOnly = true;
    divContentAttribute.style.visibility = "visible";

    newDiv.appendChild(divBarraNuevoAttribute);
    newDiv.appendChild(divContentAttribute);
    newDiv.style.visibility = "visible";
    /*newDiv.appendChild(newInput);

    newDiv.appendChild(labeltipoDato);
    newDiv.appendChild(inputTipoDato);

    newDiv.appendChild(newlabelValue);
    newDiv.appendChild(valueInput);*/

    contenedor.appendChild(newDiv);
}

function deleteAttribute(e){
   var buttonClicked = e.target;
   buttonClicked.parentElement.parentElement.remove();
}

function showAndHide(e){        
   var buttonClicked = e.target;
   var divElement = buttonClicked.parentElement;
   
   //minimizeAttribute
   var valorelem1 = document.getElementById('minimizeAttribute');
   if(divElement.parentElement.children[1].style.visibility == "visible"){
       divElement.parentElement.children[1].style.visibility = "hidden";
       divElement.parentElement.children[1].style.display = "none";
       buttonClicked.value= '˅';
   }
   else
   { 
       divElement.parentElement.children[1].style.visibility = "visible";
       divElement.parentElement.children[1].style.display = "block";
       buttonClicked.value= '˄';
   }
  
}
function onChangeTypeData(e){
  var changeData = e.target
  e.target.parentElement.children[3].type = changeData.value
}
</script>

{% include "core/confirmationModal.html" %}


{% endblock content %}

templates/documents/modal_attribs.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Launch static backdrop modal
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Understood</button>
        </div>
      </div>
    </div>
  </div>
  

templates/documents/myDocs.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Mis publicaciones{% endblock title %}

{% block content %}

{% for doc in myDocs  %}
{{doc.titulo}}
{% endfor %}


{% endblock content %}