Documents/urls.py
from django.http import * 
from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.urls import path 
from .views import *


app_name = 'documentos'

urlpatterns = [
     path('', index, name="documentos"),
     path('create/<tipo>', create, name='create'),
     path('choose/', choose_document, name='chooseType'),
     path('edit/<codigo>', edit, name='edit'),
     path('details/<id>', get_document, name='details'),
     path('createCategory/', createCategory, name='createCategory'),
     path('categories/', getCategories, name='categories'),
     path('editCategoryType/<id>', editCategory, name='editCategoryType'),

     
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import *
from core import settings
from django.conf.urls.static import static

from .views import *
urlpatterns = [
    path('', home , name='home'),
    path('Admin/', admin.site.urls),
    path('Signin/', signin, name='signin'),
    path('Signup/', signup, name='signup'),
    path("Logout/",signout, name="logout"),
    path('users/', users, name='users'),
    # path('editUser/<id>', editUser, name='editUser'),
    
    path('users/edit/<id>', modifyUser, name='usersModify'),
    
    path('myProfile/', myProfile, name='myProfile'),

    path('Documentos/', include('Documents.urls'),name='documentos'),
    path('Usuarios/', include('users.urls', namespace='usuarios')),
    
    path('users/create/', createUser, name='createUser'),


    
    path('oauth/', include('social_django.urls', namespace='social')),  

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# =======
# """core URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/3.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path,include
# from django.shortcuts import *
# from core import settings
# from django.conf.urls.static import static

# from .views import *
# urlpatterns = [
#     path('', home , name='home'),
#     path('Admin/', admin.site.urls),
#     path('Signin/', signin, name='signin'),
#     path('Signup/', signup, name='signup'),
#     path("Logout/",signout, name="logout"),
#     path('Documentos/', include('Documents.urls'),name='documentos'),
#     path('Usuarios/', include('users.urls', namespace='usuarios')),
#     path('usuarios/', include('users.urls', namespace='usuarios')),
#     path('oauth/', include('social_django.urls', namespace='social')),  

# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# >>>>>>> master

users/urls.py
from django.http import * 
from django.conf import settings
from .views import *
from django.urls import path 

app_name = 'users'

urlpatterns = [
    path('', index, name='index'),
    path('create/', create, name='create'),
    path('edit/<user>/', edit, name='edit'),
    path('delete/<int:user>', delete, name='delete'),
]

 

users/models.py
from django.db import models

# Create your models here.
class Rol(models.Model):
    idrol = models.IntegerField(primary_key=True)
    nombrerol = models.CharField(max_length=15, blank=True, null=True)
    descripcion = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'rol'


class Usuario(models.Model):
    idusuario = models.IntegerField(primary_key=True)
    idrol = models.ForeignKey(Rol, models.DO_NOTHING, db_column='idrol')
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    correo = models.CharField(unique=True, max_length=50)
    fechanacimiento = models.TimeField()
    contrasenia = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'usuario'



core/forms.py
from django import forms
from django.contrib.auth.models import User
from core.CHOICES import *

class FrmCreateUser(forms.ModelForm):
    class Meta: 
        model = User
        fields = ['username', 'first_name', 'last_name', 'email','type', 'password']
        labels = {
            'username': 'Nombre de Usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email' : 'Correo Electrónico',
            'type' : 'Tipo de Usuario', 
            'password': 'Contraseña', 
        }
        
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
            'type': forms.Select(choices=TYPE_CHOICES, attrs={'class':'form-select'}),
            'password': forms.PasswordInput(attrs={'class':'form-control'}),

        }
        

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import make_password
from psycopg2 import IntegrityError
from Documents.models import Documento, Tipodocumento
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from core.forms import *
import os

def signin(request):
    if request.method == 'GET':
        return render(request,'core/login.html',{'form': AuthenticationForm})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password1'])
        if user is None:
            return render(request,'core/login.html',{'form': AuthenticationForm,'error': 'El usuario y la contrasenia son incorrectos'})
        else:
            login(request, user)
            return redirect('home')


def signup (request):
    
    modal=  ["Registro de usuario","¿Desea guardar los datos?","No","Guardar"]
    
    if request.method == 'GET':
        return render(
            request,
            'core/signup.html',
            {
            'modal':modal
                
            }
        )
              
    else:
        if request.POST['password1'] == request.POST['password2']:
                # registrar usuario
                user = User.objects.create_user(
                    username=request.POST.get("username", "default value"),
                    password=request.POST.get('password1', "default value")
                    
                )
                user.first_name = request.POST.get("name", "default value")
                user.last_name = request.POST.get("lastname", "default value")
                user.email = request.POST.get("email", "default value")
                user.is_active = True
                user.is_superuser = True
                
                if not request.user.is_superuser:
                    user.type = 'CRE'
                user.save()
                
                return redirect('home')
                
                # return render(
                #     request,
                #     'core/signup.html',
                #     {
                #         'form': UserCreationForm,
                #         'error': 'Ya existe el usuario'
                #     }
                # )
        else:
            return render(
                request,
                'core/signup.html',
                {
                    'form': UserCreationForm,
                    'error': 'Las contrasenias no coinciden'
                }
        )    

def signout(request):
        logout(request)
        return render(request,'core/login.html')


@login_required(login_url='signin')
def home(request):
      
    tipos = Tipodocumento.objects.all() 
    #Home muestra los documentos que fueron establecidos:      
    docs = Documento.objects.all()

    searchKey = request.POST.get("key", "searchKey")
    
    for doc in docs:        
        if(doc.portada):
            if(os.path.exists(os.getcwd() + doc.portada.url) == False):
                doc.portada = doc.idtipodocumento.imagen
        else:
            doc.portada = doc.idtipodocumento.imagen
            
    texto = request.GET.get('texto')
    
    todo_seleccionado = request.GET.get('allSelected')

    documentosMarcados = request.GET.getlist('activo') 
    documentosMarcadosDos = request.GET.getlist('activo') 

    for tipo in tipos:
        tipo.activado = True

    if (todo_seleccionado == "true"):
            for tipo in tipos:
                documentosMarcados.append(tipo.idtipodocumento)

    if documentosMarcados:
        for tipo in tipos:
            encontrado = False
            for idtipo in documentosMarcados:
                if  tipo.idtipodocumento == int(idtipo):
                    encontrado = True
            tipo.activado = encontrado            
    
    searchKey = request.GET.get("key", "searchKey")
    if not documentosMarcados:
        for tipo in tipos:
            documentosMarcados.append(tipo.idtipodocumento)
    
    if texto != None:
        docs = docs.filter(titulo__contains = texto, idtipodocumento__in = documentosMarcados)
    else:
        texto = ""
        docs = docs.filter(titulo__contains = "", idtipodocumento__in = documentosMarcados)

    #Verificar que exista la imágen de los documentos, si no existe usar la de la categoría.
    for doc in docs:
        if(doc.portada):
            if(os.path.exists(os.getcwd() + doc.portada.url) == False):
                doc.portada = doc.idtipodocumento.imagen
        else:
            doc.portada = doc.idtipodocumento.imagen 



    if (todo_seleccionado == "true"):
        if documentosMarcadosDos:
            for tipo in tipos:
                encontrado = False
                for idtipo in documentosMarcadosDos:
                    if  tipo.idtipodocumento == int(idtipo):
                        encontrado = True
                tipo.activado = encontrado        
    else:
        todo_seleccionado = "false"

    max_elements_per_page = 6

    paginator = Paginator(docs, max_elements_per_page)
    page_number = request.GET.get('page') or 1
    page_obj = paginator.get_page(page_number)

    div_agregar= []
    if max_elements_per_page % 2 != 0:
        max_elements_per_page = max_elements_per_page + 2
    div_agregar.append(range(max_elements_per_page-len(docs)))
    return  render(request,'core/home.html',{'todo_seleccionado': todo_seleccionado, 'div_agregar': div_agregar, 'texto':texto, 'docs':page_obj, 'categories': tipos, 'page_obj': page_obj, 'searchKey': searchKey})

def users (request): 
    if request.user.type == 'ADM':
        users = User.objects.all()
        return render(request,'core/users.html',{'users':users})
    else: return redirect('home')
    
    
# def editUser(request, id):
#     modal=  ["Editar documento","¿Desea guardar cambios?","Cancelar","Guardar"]
#     if request.user.is_superuser:
#         user = User.objects.get(id=id)
        
#         return render(request,'core/editUser.html',{'user':user})
    

def myProfile(request):
    modal=  ["Modificar usuario","¿Desea guardar cambios?","Cancelar","Modificar"]
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.get(id=request.user.id)
            user.first_name = request.POST.get("name", "default value")
            user.last_name = request.POST.get("lastname", "default value")
            user.email = request.POST.get("email", "default value")
            user.username = request.POST.get("username", "default value")
            user.set_password(request.POST.get("password1", "default value"))
            user.save()
            messages.add_message(request, messages.INFO, 'Usuario modificado correctamente')
            
            return redirect('home')
        
        else: 
            return render(request,'core/home.html',{'user':user, 'modal':modal})

    
        
    else:
        if request.user.is_authenticated:
            user = User.objects.get(id=request.user.id)
            return render(request,'core/myProfile.html',{'user':user,  'modal':modal})
        else:
            return render(request,'core/login.html',{'form': AuthenticationForm})

def createUser(request):
    modal=  ["Crear Usuario","¿Desea guardar cambios?","Cancelar","Guardar"]
    
    frm = FrmCreateUser
    if request.method ==  'POST':
        frm = FrmCreateUser(request.POST)
        if frm.is_valid():
            
            frm.cleaned_data["password"] = User.set_password(request.POST.get("password", "default value"))
            
            frm.save()  
                   
            messages.add_message(request, messages.SUCCESS, 'Usuario creado correctamente')
            return redirect('home')
        else:
            return render(request,'core/createUser.html',{'form':frm, 'modal':modal})
    else:
        return render(request,'core/createUser.html',{'form':frm, 'modal':modal})
    
def modifyUser(request, id):
    modal=  ["Crear Usuario","¿Desea guardar cambios?","Cancelar","Guardar"]
    
    user = User.objects.get(id=id)
    frm = FrmCreateUser(instance=user)
    
    if request.method ==  'POST':
        frm = FrmCreateUser(request.POST)
        if frm.is_valid():
            userActual = User.objects.get(id=id)

            passwordEdit = userActual.password
            print("NUEVA CONTRASENIA = ", request.POST.get("password"))
            print("NUEVA CONTRASENIA = ", request.POST.get("password"))
            print("NUEVA CONTRASENIA = ", request.POST.get("password"))
            print("NUEVA CONTRASENIA = ", request.POST.get("password"))
            print("NUEVA CONTRASENIA = ", request.POST.get("password"))

            if (request.POST.get("password") != ''):
                userActual.set_password(request.POST.get("password"))
                passwordEdit= userActual.password

            user = User(id = user.id, type = request.POST.get("type", userActual.type),
                        email = request.POST.get("email", userActual.email),
                        username=request.POST.get("username", userActual.username),
                        first_name = request.POST.get("first_name", userActual.first_name),
                        last_name = request.POST.get("last_name", userActual.last_name),
                        password = passwordEdit)
            

            print(passwordEdit)

users/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'users/index.html')

def create(request): 
    if request.method == 'POST':
        pass
    return render(request,'users/create.html')

def edit(request, user):
    user = {'name': 'Juan', 'last_name': 'Perez', 'email': 'mack@@@.com'}    
    if request.method == 'POST':
        pass
    
    return render(request,'users/update.html', {'user': user})

def delete(request):
    if request.method == 'POST':
        pass
    return render(request,'users/delete.html')



    
    


templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <link rel='icon' typy='image/jpg' href={% static 'img/favicon.png' %}>


    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
  


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@500&display=swap"
      rel="stylesheet"
    />


    <script>
      function mostrarPassword(){
        var cambio = document.getElementById("password1");
        if(cambio.type == "password"){
          cambio.type = "text";
          $('.icon').removeClass('fa fa-eye-slash').addClass('fa fa-eye');
        }else{
          cambio.type = "password";
          $('.icon').removeClass('fa fa-eye').addClass('fa fa-eye-slash');
        }
      }
      function mostrarPassword2(){
        var cambio = document.getElementById("password2");
        if(cambio.type == "password"){
          cambio.type = "text";
          $('.icon').removeClass('fa fa-eye-slash').addClass('fa fa-eye');
        }else{
          cambio.type = "password";
          $('.icon').removeClass('fa fa-eye').addClass('fa fa-eye-slash');
        }
      }
    </script>

  </head>
  <body>
    
    {% include 'core/navbar.html' %}
    {% include 'core/messages.html' %}
    <div class="main">
      {% block content %}
      
    
      {% endblock content %}
    </div>

{% include 'core/footer.html' %}

 



    

  </body>
</html>

templates/core/confirmationModal.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/confirm-modal.css' %}" />
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">{{modal.0}}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {{modal.1}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{modal.2}}</button>
        <button  id="confirm" type="button" class="btn btn-primary">{{modal.3}}</button>
      </div>
    </div>
  </div>
</div>




{% comment %} 
<!-- Modal -->
<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="confirm-modal modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">{{modal.0}}</h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">{{modal.1}}</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          {{modal.2}}
        </button>
        <button id="confirm" type="button" class="btn btn-primary">
          {{modal.3}}
        </button>
      </div>
    </div>
  </div>
</div> {% endcomment %}
<script>
  let saveButton = document.getElementById("confirm");

  saveButton.onclick = function () 
  {
    document.getElementById("form-main").submit();
  }

</script>

templates/core/createUser.html
{% extends 'core/base.html' %} {% block content %}
{% block title %}Crear usuario{% endblock title %}

<div
  class="bg-image row d-flex justify-content-center align-items-center vh-100"
>
  <div class="col-sm-12 col-md-6 col-lg-5 col-xl-4">
    <form
      id="form-main"
      class="p-5 shadow rounded-5 bg-light login-container"
      action="{% url 'createUser' %}"
      method="POST"
      class="card card-body"
    >
    {% csrf_token %}
      <h1 class="text-center">Crear usuario</h1>

      {{form}}

      <input  class= "btn btn-primary"  value="Guardar" data-bs-toggle="modal" data-bs-target="#exampleModal" >

    </form>
  </div>
</div>
{% include "core/confirmationModal.html" %}
{% endblock content %}

templates/core/footer.html
<footer class="footer text-white  fixed-bottom">
  <div class="container">
    <div class="text-center">
      <div class="col-md-12">
        <p>Sistema de gestión de documentos</p>
      </div>
    </div>
  </div>
</footer>
<!-- Fin Footer 

templates/core/home.html
{% extends "core/base.html" %} {% load static %}
{% block title %}Inicio{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

<!Crear dos columnas una para el nav y la otra para los libros>
  <form action="" method="get" role="search" style="margin-bottom: 3%; ">
    <div class="row justify-content-md-center" style=" margin-bottom: 2%; margin-top: 2%;">

      <div class="col order-first col-sm-10">
        <input class="form-control me-2" type="search" name="texto" placeholder="Buscar" value="{{texto}}"
          aria-label="Search"
          style="color: #280886; margin-left: 10px; font-size:30px; border: 0cap; font-weight: 600; ">
      </div>
      {% include "documents/pagination_book.html" %}

      <div class=" col col-auto order-last align-items-center">
        <button class=" btn " type="submit" style=" margin-bottom: 5%;"><i class='bx bx-search'
            style='color:#3b57e8; font-size:50px ;'></i>
        </button>
      </div>

    </div>

    <div class="row ">
      <div class="container-categories col-auto border rounded offset-3" style="margin-left: 3%; background-color: #dfd4fe;">
        <!NAV izquierdo>
        
          <ul class="navbar-nav p-3" style="margin-top: 10%;">
            <p><i class='bx bx-category' style='color:#12043e'></i> Categorias </p>
            {% csrf_token %}

            <div class="form-check form-switch mt-1" style=" margin-bottom: 2%;">
              <li>
                <input checked class="form-check-input" type="checkbox" role="switch" id="chk-{{cat.idtipodocumento}}">
                <label class="form-check-label" for="chk-{{cat.idtipodocumento}}">Todas</label>
                <!hr class="divider">
              </li>

            </div>
            {% for cat in categories %}
            <div class="form-check form-switch" style=" margin-bottom: 5%;">
              {% if cat.activado == True %}
              <input checked name="activo" value="{{cat.idtipodocumento}}" class="form-check-input" type="checkbox"
                role="switch" id="chk-{{cat.idtipodocumento}}">
              {% else %}
              <input name="activo" value="{{cat.idtipodocumento}}" class="form-check-input" type="checkbox"
                role="switch" id="chk-{{cat.idtipodocumento}}">
              {% endif %}
              <label name="categoria" class="form-check-label" for="chk-{{cat.idtipodocumento}}">{{cat.tipo}}</label>
              <li>
                <!hr class="divider">
              </li>
              <input type="hidden" name="idCategoria" value="{{cat.idtipodocumento}}" />
            </div>
            {% endfor %}

          </ul>

      </div>
      <div class="col">
        <div class="container">
          <div class="docs-container row  justify-content-md-center">

            <!Desde aqui generar>
              {% for item in docs %}
              <div class="col " style="display: flex;
              align-items: center;
              justify-content: center;">
                <!Libro 1>
                  <div class="containerima" style="max-width: 300px; position: relative; margin-top: 4%;"
                    aria-hidden="true">
                    <img class="portadadeg" width="300" height="375" src="{{item.portada.url}}">
                    <div class="content">
                      <p>
                        <a class="titulos-libros" href="/Documentos/details/{{item.iddocumento}}"
                          style=" color: #dfdfdf;  font-size: 20px; font-weight: 900; ">{{item.titulo}}</a>
                      </p>
                    </div>
                  </div>
              </div>
              {% endfor %}
              <!Hasta aqui generar>
                {% for item in div_agregar %}
                {% for i in item %}
                <div class="col">
                  <!Libro 1>
                    <div class="containerima" style="max-width: 300px; position: relative; margin-top: 4%;"
                      aria-hidden="true">

                    </div>
                </div>
                {% endfor %}
                {% endfor %}

          </div>
        </div>
      </div>
    </div>
  </form>

  <style>
    .containerima::after {
      position: absolute;
      top: 0px;
      left: 0px;
      content: '';
      background-image: linear-gradient(#410ED3, #280886);
      width: 100%;
      height: 100%;
      filter: blur(10px);
      z-index: -1;
    }
  </style>
  <div style="margin-bottom: 5%;"></div>

 
  {% endblock content %}

templates/core/index.html
{% extends "core/base.html" %} {% load static %} 

{% block content %}

<div class="container">
  <div class="row">

    <div class="col col-lg-2 col-md-4 col-sm-1 card">sdfsf</div>
    <div class="col col-lg-2 col-md-4 col-sm-1 card">sdfsf</div>
    <div class="col col-lg-2 col-md-4 col-sm-1 card">sdfsf</div>
    <div class="col col-lg-2 col-md-4 col-sm-1 card">sdfsf</div>
    <div class="col col-lg-2 col-md-4 col-sm-1 card">sdfsf</div>
    <div class="col col-lg-2 col-md-4 col-sm-1 card">sdfsf</div>
    <div class="col col-lg-2 col-md-4 col-sm-1 card">sdfsf</div>
    <div class="col col-lg-2 col-md-4 col-sm-1 card">sdfsf</div>
    
  </div>
</div>

{% endblock content %}


templates/core/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li id="myAlert" {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>

<script>
    // Esperar 5 segundos (5000 milisegundos) y luego cerrar el alert
    setTimeout(function() {
      var myAlert = document.getElementById('myAlert');
      var bsAlert = new bootstrap.Alert(myAlert);
      bsAlert.close();
    }, 3000);
  </script>

{% endif %}

templates/core/modUser.html
{% extends 'core/base.html' %} {% block content %}
{% block title %}Modificar Usuario{% endblock title %}

<div
  class="bg-image row d-flex justify-content-center align-items-center vh-100"
>
  <div class="col-sm-12 col-md-6 col-lg-5 col-xl-4">
    <form
      id="form-main"
      class="p-5 shadow rounded-5 bg-light login-container"
      action="{% url 'usersModify' id=id %}"
      method="POST"
      class="card card-body"
    >
    {% csrf_token %}
      <h1 class="text-center">Modificar Usuario</h1>

      {{form}}

      <input  class= "btn btn-primary"  value="Guardar" data-bs-toggle="modal" data-bs-target="#exampleModal" >

    </form>
  </div>
</div>
{% include "core/confirmationModal.html" %}
{% endblock content %}

templates/core/navbar.html


<nav class="navbar navbar-expand-lg bg-body-tertiary pt-0 fixed-top p-0 m-0 ">
  <div class="container-fluid mt-0 " style= "background-color: #1B7505; height:100% ">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Inicio</a>
          
        </li>

        <!-- <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Documentos</a>
        </li> -->

        {% if  user.type == 'CRE' or user.type == 'ADM' or user.type == 'MOD' %}
        
          <li class="nav-item dropdown">

            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"  style="color: aliceblue;">
              Mi documentos
            </a>


            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'documentos:documentos' %}">Ver mis documentos</a></li>
              <li><a class="dropdown-item" href="{% url 'documentos:chooseType' %}" >Subir documento</a></li>
              <li><hr class="dropdown-divider"></li>
            </ul>
          </li>
        {% endif %}
        

          {% comment %} --------------Admin----------------- {% endcomment %}

        {% if user.type == 'ADM' %}
          <li class="nav-item dropdown">

            <a  style="color: aliceblue;" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Mantenimiento
            </a>


            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'documentos:categories' %}">Categorias</a></li>
              <li><a class="dropdown-item" href="{% url 'users' %}">Usuarios</a></li>

              <li><a class="dropdown-item" href="{% url 'signin' %}" ></a></li>
              <li><hr class="dropdown-divider"></li>
            </ul>
          </li>
        {% endif %}


       


        <li class="nav-item dropdown">
          <a  style="color: aliceblue;" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Sesión
          </a>
          <ul class="dropdown-menu">

            <li>{{user.first_name}}</li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a></li>
            <li><a class="dropdown-item" href="{% url 'myProfile' %}">Ver perfil</a></li>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>